<!DOCTYPE html>
<html>
<head>
    <title>User Profile PDF</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 14px;
            color: #333;
            margin: 40px;
        }
        h2 {
            color: #2c3e50;
            text-align: center;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        .profile-table {
            width: 100%;
            border-collapse: collapse;
        }
        .profile-table th,
        .profile-table td {
            padding: 12px;
            text-align: left;
            vertical-align: top;
        }
        .profile-table th {
            width: 30%;
            background-color: #f0f0f0;
            font-weight: bold;
        }
        .technologies-list {
            margin: 0;
            padding-left: 18px;
        }
        .footer {
            text-align: center;
            margin-top: 50px;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>
    <h2>User Profile</h2>

    <table class="profile-table">
        <tr>
            <th>Full Name</th>
            <td>{{ $user->first_name }} {{ $user->last_name }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>Experience</th>
            <td>{{ $user->experience }} {{ $user->experience == 1 ? 'year' : 'years' }}</td>
        </tr>
        <tr>
            <th>Technologies Interested</th>
            <td>
                <ul class="technologies-list">
                    @foreach (json_decode($user->technologies_interested) as $tech)
                        <li>{{ $tech }}</li>
                    @endforeach
                </ul>
            </td>
        </tr>
    </table>

    <div class="footer">
        Generated by Laravel PDF System | {{ now()->format('F d, Y') }}
    </div>
</body>
</html>
